spring:
  kafka:
    bootstrap-servers: localhost:9093


app:
  kafka:
    kafkaOrderMessageTopic: "order-topic" # назввание топика
    kafkaStatusOrderMessageTopic: "order-status-topic"
    kafkaMessageGroupId: "kafka-message-group-id2" # тут меняем имя, если это другое приложение.
    kafkaOffsetValue: "latest" #"latest" - в конец or "earliest" - в начало, Но ни на что не влияет!!!!.
    kafkaListenerAutoStartup: "true" #"false" or "true"


